version: '3'

services:
  opensearch:
    image: opensearchproject/opensearch:1.0.0
    container_name: opensearch
    environment:
      - discovery.type=single-node
      - plugins.security.ssl.http.enabled=false
      - http.cors.enabled=true
      - http.host=0.0.0.0
      - http.port=9200
      - "http.cors.allow-origin=*"
      - "http.cors.allow-credentials=true"
      - "http.cors.allow-headers=X-Requested-With,X-Auth-Token,Content-Type,Content-Length,Authorization"
    ports:
      - 9200:9200
    volumes:
      - opensearch-data:/usr/share/opensearch/data
    networks:
      - opensearch-network

  opensearch-dashboards:
    image: opensearchproject/opensearch-dashboards:1.0.0
    container_name: opensearch-dashboards
    environment:
      - OPENSEARCH_HOSTS=http://opensearch:9200
    ports:
      - 5601:5601
    networks:
      - opensearch-network

networks:
  opensearch-network:

volumes:
  opensearch-data:
